dynamic-blog/DynamicBlog/DynamicBlog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

dynamic-blog/DynamicBlog/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # path to url with all blog objects listed
    path('archive', views.archive, name='archive'),
    # initializes the database
    path('init', views.init, name='init'),
    # single blog object with id='<int:blog_id>' and it's comments
    path('<int:blog_id>/', views.detail, name='detail'),
    # post comment to a blog object
    path('<int:blog_id>/comment', views.postcomment, name='comment'),
    # wipe the database
    path('sepuku', views.sepuku, name='sepuku'),
    # straight to the index page
    path('', views.index, name='index'),

    # path to the about page, deprecated now
    path('about', views.about, name='about'),
    # tips page, deprecated now
    path('tips', views.tips, name='tips'),
]

dynamic-blog/DynamicBlog/blog/models.py
from django.db import models

class Blog(models.Model):
    # content
    content = models.CharField(max_length=1024)
    # title
    title   = models.CharField(max_length=100)
    # author of post
    author  = models.CharField(max_length=32)
    # date published
    pub_date = models.DateTimeField()
    # when queried, show its id and it's title
    def __str__(self):
        return (str(self.id) + " " + str(self.title))


class Comment(models.Model):
    # foreign key
    blog_fk = models.ForeignKey(Blog, related_name='comments' ,on_delete=models.CASCADE)
    # title of comment
    title   = models.CharField(max_length=100)
    # author of comment
    author  = models.CharField(max_length=32)
    # date commented
    pub_date = models.DateTimeField()
    # the meat of the post
    content = models.CharField(max_length=1024)
    # when queried, show the fk to the Blog and the title of the comment
    def __str__(self):
        return (str(self.blog_fk) + " " + self.title)
    

dynamic-blog/DynamicBlog/blog/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

from time import strftime, time
import datetime
import random

from .models import Blog, Comment

from .functions import randomIpsumBlog, randomIpsumComment, randomIpsumWord

# returns the index page with 3 blog objects from the databse
def index(request):
    # says to go to the index page and returns the 
    # time and the las three blogs posted
    return render(request, 
            'blog/index.html',
            { 
                # the current time
                'now': datetime.datetime.now(),
                # the three latest blogs
                'blogs': Blog.objects.order_by('-pub_date')[:3]
                })

# returns the aboutMe page 
def about(request):
    return render(request,
            'blog/aboutMe.html',
            # the current time
            { 'now': datetime.datetime.now() })

# returns the tip page
def tips(request):
    return render(request, 
            'blog/techTips.html',
            # the current time
            { 'now': datetime.datetime.now() })

# fills the database with 6 Blog objects
def init(request):
    #--------------------------------------------------------------------------------------#
    # delete all blog objects and their comments (Can be Removed and Just Use blog/sepuku) #
    #--------------------------------------------------------------------------------------#
    for b in Blog.objects.all():
        b.delete()
    #--------------------------------------------------------------------------------------#

    # seeds it with a constantly changing seed
    random.seed(datetime.datetime.now())
    #generates 10 blogs with five comments each
    for i in range(10):
        # create a single Blog object
        blogObj = Blog(content=str(randomIpsumBlog()),
                # title is generic except for a single LI word
                title = "Post About " + str(randomIpsumWord()),
                # username is generic except for a number
                author = "cool_guy" + str(random.randint(11, 99) + 1) + "@overcompensating.oops",
                # said it's published like right now
                pub_date = timezone.now())
        blogObj.save()
        # three comments will be attached to Blog b
        for j in range(5):
            c = Comment(title="comment_" + str(j + 1),
                        # almost completely generic email
                        author = "notRussianBot" + str(random.randint(11, 99) + 1) + "@totally.notrussia",
                        # it's publishing date is rn
                        pub_date = timezone.now(),
                        # the meat of the comment
                        content = randomIpsumComment(),
                        # the foreign key to the Blog object
                        blog_fk = blogObj)
            c.save()
    return HttpResponseRedirect(reverse('blog:index'))

# cleans all Blog objects (and their comments) from the database
def sepuku(request):
    # delete all blog objects and their comments
    for b in Blog.objects.all():
        b.delete()
    # return user to the index page
    return redirect('blog:index')

# shows all the blog posts in the database
def archive(request):
    return render(request,
            'blog/archive.html',
            {
                # send in all the blogs from latest to oldest
                'blogs': Blog.objects.order_by('-pub_date')
                })

# show a single untruncated blog post with comments underneath
def detail(request, blog_id):
    # get a single blog object
    b = Blog.objects.all().get(id=blog_id)

    return render(request, 
            'blog/detail.html',
            { 
                # Single blog object
                'blog': b,
                # all comments associated with the blog object above
                'comments': b.comments.all().order_by('-pub_date'),
                })

# grab data from the comment form and create a Comment object from it
def postcomment(request, blog_id):
    #generic comment
    comment = Comment()
    # fk is the blog whose id we passed in
    comment.blog_fk = Blog.objects.all().get(pk = blog_id)
    # title was passed in POST
    comment.title = request.POST['title']
    # author was passed in POST
    comment.author = request.POST['user_mail']
    # get time as of right now
    comment.pub_date = datetime.datetime.now()
    # content from POST
    comment.content = request.POST['user_message']

    # save the comment created above
    comment.save()

    # redirect the user to the original detail page
    return HttpResponseRedirect(reverse('blog:detail', args=(blog_id,)))

dynamic-blog/DynamicBlog/blog/templates/blog/aboutMe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--==================-->
<!-- The Head Section -->
<!--==================-->

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
	<title>About Me</title>
</head>

<body>
	<div class="linksection">
		<p>
			<a class="links" href="{% url 'index' %}">
				<img id="homeicon" alt="icon of a home" src="{% static "blog/home_icon.png" %}">Home</a>

            <a class="links" href="{% url 'archive' %}">
				<img id="scrollicon" alt="picture scroll" src="{% static "blog/scroll_icon.png" %}">Archive</a>

            {% comment %} <a class="links" href="{% url 'sepuku' %}">
                <img id="bombicon" alt = "icon of bomb" src="{% static "blog/bomb_icon.png" %}">Nuke It</a> {% endcomment %}

            <a class="links" href="{% url 'init' %}">
                <img id="babyicon" alt = "icon of baby" src="{% static "blog/baby_icon.png" %}">Init</a>

			{% comment %} <a class="links" href="{% url 'about' %}">
				<img id="rrhead" alt="robbie rotten's head" src="{% static "blog/rr_head.png" %}">About Me</a> {% endcomment %}  
        </p>
	</div>
	<!-- <br> -->
	<!--================-->
	<!-- The Page Title -->
	<!--================-->
	<h1 id="aboutmetitle">About Me:</h1>
	<h4 id="datetime">The current time is: {{ now }}</h4>

	<!--==================-->
	<!-- The Box of Links -->
	<!--==================-->


	<!--================-->
	<!-- Portrait Image -->
	<!--================-->
	<div id="portraitbox" style="text-align: center">
		<img id=portrait src="{% static "blog/rr_portrait.jpg"%}" alt="robbie rotten portrait" height="300">
	</div>


	<!--==================-->
	<!-- Bio Text Section -->
	<!--==================-->
	<div class="biographicalsketch">
		<h3>Biographical Sketch</h3>
		<p>In pellentesque, turpis eget convallis faucibus, ligula dolor vehicula ipsum, vitae gravida justo arcu porta magna. Etiam
			rutrum placerat enim at laoreet. Nullam id odio elit. Integer aliquam, nisi id tristique pretium, odio ipsum tempor metus,
			non semper turpis enim ac ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
			Sed ultrices, est a rhoncus suscipit, velit libero semper magna, eu imperdiet nunc nunc vel odio. Integer vel enim cursus,
			egestas ex eget, maximus risus. Vivamus fringilla blandit sem a placerat. Etiam non sodales libero, ut pharetra nisl.
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam blandit leo nunc, vel euismod lorem faucibus quis.</p>
	</div>

	<!--==================-->
	<!-- Interest Section -->
	<!--==================-->
	<h3>My Interests:</h3>
	<!-- Data for the Favorite Animal -->
	<h4>Favorite Animal:</h4>
	<img src="{% static "blog/rr_cow.PNG"%}" alt="robbie rotten as a cow" height="200">
	<!-- Data for Activities -->
	<h4>Favorite Activities:</h4>
	<img src="{% static "blog/rr_balloon.PNG"%}" alt="robbie rotten tying balloon animals" height="200">
	<img src="{% static "blog/rr_parachute.PNG"%}" alt="robbie rotten parachuting" height="200">
	<img src="{% static "blog/rr_climbing.PNG"%}" alt="robbie rotten climbing a tree" height="200">
	<br>

	<!--===========================-->
	<!-- Data for the Catch Prases -->
	<!--===========================-->
	<h3>Catch Phrases:</h3>
	<ol id="catchlist">
		<li>LazyTown is the laziest town on the planet, and I'm gonna keep it that way!</li>
		<li>Now kids, stand up, turn your book around, sit down AND... fall asleep</li>
		<li>This will be as easy as stealing candy from a baby, and I should know.</li>
		<li>Click click as fast as you can! You can't catch me, I'M COMPUTERIZED MAN!</li>
	</ol>
</body>

</html>

dynamic-blog/DynamicBlog/blog/templates/blog/archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--==================-->
<!-- The Head Section -->
<!--==================-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
    <title>Archive</title>
</head>

<body>
    <div class="linksection">
		<p>
			<a class="links" href="{% url 'blog:index' %}">
				<img id="homeicon" alt="icon of a home" src="{% static "blog/home_icon.png" %}">Home</a>

            <a class="links" href="{% url 'blog:archive' %}">
				<img id="scrollicon" alt="picture scroll" src="{% static "blog/scroll_icon.png" %}">Archive</a>

            {% comment %} <a class="links" href="{% url 'blog:sepuku' %}">
                <img id="bombicon" alt = "icon of bomb" src="{% static "blog/bomb_icon.png" %}">Nuke It</a> {% endcomment %}

            <a class="links" href="{% url 'blog:init' %}">
                <img id="babyicon" alt = "icon of baby" src="{% static "blog/baby_icon.png" %}">Init</a>
			{% comment %} <a class="links" href="{% url 'about' %}">
				<img id="rrhead" alt="robbie rotten's head" src="{% static "blog/rr_head.png" %}">About Me</a> {% endcomment %}  
        </p>
	</div>
    <div class="blogpostsection">
        <!--================-->
        <!-- The Page Title -->
        <!--================-->
        <h1>Archive:</h1>
	    {% comment %} <h4 id="datetime">The current time is: {{ now }}</h4> {% endcomment %}
            {% for b in blogs %}
            <article>
                <h2><a href = "{% url 'blog:detail' b.id %}"> {{b.title}}</a></h2>
                <strong> Posted at {{ b.pub_date|date:'Y-m-d H:i:s' }} by {{b.author}}</strong>
                <p> {{b.content|truncatewords:200}} </p>
                <div class="commentsection">
                    <p> <a href = "{% url 'blog:detail' b.id %}">{{b.comments.count}} Comments</a> </p>
                </div>
            </article>
            {% endfor %}
    </div>
</body>

</html>

dynamic-blog/DynamicBlog/blog/templates/blog/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--==================-->
<!-- The Head Section -->
<!--==================-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
    <title>Main Page</title>
</head>

<body>
    <div class="linksection">
		<p>
			<a class="links" href="{% url 'blog:index' %}">
				<img id="homeicon" alt="icon of a home" src="{% static "blog/home_icon.png" %}">Home</a>

            <a class="links" href="{% url 'blog:archive' %}">
				<img id="scrollicon" alt="picture scroll" src="{% static "blog/scroll_icon.png" %}">Archive</a>

            {% comment %} <a class="links" href="{% url 'blog:sepuku' %}">
                <img id="bombicon" alt = "icon of bomb" src="{% static "blog/bomb_icon.png" %}">Nuke It</a> {% endcomment %}

            <a class="links" href="{% url 'blog:init' %}">
                <img id="babyicon" alt = "icon of baby" src="{% static "blog/baby_icon.png" %}">Init</a>
                
			{% comment %} <a class="links" href="{% url 'about' %}">
				<img id="rrhead" alt="robbie rotten's head" src="{% static "blog/rr_head.png" %}">About Me</a> {% endcomment %}  
        </p>
	</div>
    <div class="blogpostsection">
        <!--================-->
        <!-- The Page Title -->
        <!--================-->
        <h1>{{ blog.title }}</h1>
        <article>
            <strong> Posted at {{ blog.pub_date|date:'Y-m-d H:i:s' }} by {{blog.author}}</strong>
            <p> {{ blog.content }} </p>
            <b> {{blog.comments.count}} comments </b>

            <form action="{% url 'blog:comment' blog.id %}" method="post">
            {% csrf_token %}
                <div id="title">
                    <label for="title">Title:</label>
                    <input type="text" id="name_tag" name="title">
                </div>
                <div id="emailline">
                    <label for="mail">E-mail:</label>
                    <input type="email" id="mail_address" name="user_mail">
                </div>
                <div id="commentbody">
                    <label for="msg">Comment:</label>
                    <textarea id="msg" name="user_message"></textarea>
                </div id="submitbutton">
                    <button type="submitt">Post Comment</button>
                <div>
            </form>

            <div class="detailcommentlist">
                {% for c in comments %}
                    <h4> {{ c.title }} by <i>{{c.author}}</i> at {{c.pub_date}} </h4>
                    <p> {{ c.content }} </p>
                    <h1></h1>
                {% endfor %}
            </div>
        </article>
    </div>
</body>

</html>

dynamic-blog/DynamicBlog/blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--==================-->
<!-- The Head Section -->
<!--==================-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
    <title>Main Page</title>
</head>

<body>
    <div class="linksection">
		<p>
			<a class="links" href="{% url 'blog:index' %}">
				<img id="homeicon" alt="icon of a home" src="{% static "blog/home_icon.png" %}">Home</a>

            <a class="links" href="{% url 'blog:archive' %}">
				<img id="scrollicon" alt="picture scroll" src="{% static "blog/scroll_icon.png" %}">Archive</a>

            {% comment %} <a class="links" href="{% url 'blog:sepuku' %}">
                <img id="bombicon" alt = "icon of bomb" src="{% static "blog/bomb_icon.png" %}">Nuke It</a> {% endcomment %}

            <a class="links" href="{% url 'blog:init' %}">
                <img id="babyicon" alt = "icon of baby" src="{% static "blog/baby_icon.png" %}">Init</a>

			{% comment %} <a class="links" href="{% url 'about' %}">
				<img id="rrhead" alt="robbie rotten's head" src="{% static "blog/rr_head.png" %}">About Me</a> {% endcomment %}  
        </p>
	</div>
    <div class="blogpostsection">
        <!--================-->
        <!-- The Page Title -->
        <!--================-->
        <h1>Main Page:</h1>
	    {% comment %} <h4 id="datetime">The current time is: {{ now }}</h4> {% endcomment %}
            {% for b in blogs %}
            <article>
                <h2><a href = "{% url 'blog:detail' b.id %}"> {{b.title}}</a></h2>
                <strong> Posted at {{ b.pub_date|date:'Y-m-d H:i:s' }} by {{b.author}}</strong>
                <p> {{b.content|truncatewords:200}} </p>
                <div class="commentsection">
                    <p> <a href = "{% url 'blog:detail' b.id %}">{{b.comments.count}} Comments</a> </p>
                </div>
            </article>
            {% endfor %}
    </div>
</body>

</html>

dynamic-blog/DynamicBlog/blog/templates/blog/techTips.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--==============-->
<!-- Head Section -->
<!--==============-->

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
	<title>Tech Tips</title>
</head>

<body>
	<div class="linksection">
		<p>
			<a class="links" href="{% url 'index' %}">
				<img id="homeicon" alt="icon of a home" src="{% static "blog/home_icon.png" %}">Home</a>

            <a class="links" href="{% url 'archive' %}">
				<img id="scrollicon" alt="picture scroll" src="{% static "blog/scroll_icon.png" %}">Archive</a>

            {% comment %} <a class="links" href="{% url 'sepuku' %}">
                <img id="bombicon" alt = "icon of bomb" src="{% static "blog/bomb_icon.png" %}">Nuke It</a> {% endcomment %}

            <a class="links" href="{% url 'init' %}">
                <img id="babyicon" alt = "icon of baby" src="{% static "blog/baby_icon.png" %}">Init</a>

			{% comment %} <a class="links" href="{% url 'about' %}">
				<img id="rrhead" alt="robbie rotten's head" src="{% static "blog/rr_head.png" %}">About Me</a> {% endcomment %}  
        </p>
	</div>
	<!--===============-->
	<!-- Links Section -->
	<!--===============-->
	<h1>Tech Tips:</h1>
	<h4 id="datetime">The current time is: {{ now }}</h4>


	<br>
	<br>

	<!--===============-->
	<!-- Table Section -->
	<!--===============-->
	<div class="gittable">
		<table style="width:50%">
			<!-- Header Row -->
			<tr>
				<th>Command Name</th>
				<th>Description</th>
				<th>Example</th>
			</tr>
			<!-- First Row -->
			<tr>
				<td>git init</td>
				<td>initialize a local repository</td>
				<td>
					<code>git init</code>
				</td>
			</tr>
			<!-- Second Row -->
			<tr>
				<td>git add *.*</td>
				<td>add a file directly to remote repository</td>
				<td>
					<code>git add example.txt</code>
				</td>
			</tr>
			<!-- Third Row -->
			<tr>
				<td>git logged</td>
				<td>print out list of all previous commits</td>
				<td>
					<code>git logged</code>
				</td>
			</tr>
			<!-- Fourth Row -->
			<tr>
				<td>git fix</td>
				<td>refactor all code recursively inside local repository</td>
				<td>
					<code>git fix example-repo</code>
				</td>
			</tr>
			<!-- Fifth Row -->
			<tr>
				<td>git kill *.*</td>
				<td>remove all files referenced in the file to avoid dependency errors</td>
				<td>
					<code>git kid example.cpp</code>
				</td>
			</tr>
		</table>
	</div>
</body>

</html>